# Generated by Django 4.0 on 2021-12-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
