# Generated by Django 4.0 on 2021-12-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_poster_alter_anime_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='poster',
            field=models.ImageField(blank=True, upload_to='./'),
        ),
    ]
