# Generated by Django 4.0 on 2021-12-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='ides',
        ),
        migrations.AddField(
            model_name='ide',
            name='programming_languages',
            field=models.ManyToManyField(to='ide.ProgrammingLanguage'),
        ),
    ]
